server.address=127.0.0.1
server.port=0
server.shutdown=graceful
spring.main.banner-mode=off
spring.jackson.default-property-inclusion=non_null
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
